### ISSUE TITLE
header和body的格式是什么

### ISSUE THREAD

**Issue by BaileyZyp** [IsSuperman/Surge-js#1]
header和body的格式示例可以发一下吗？或者截图打码

**Comment by tiandongxv** [comment]
我测试很多次，一直没有成功，劳烦大佬看一下，错误出现在哪里，谢谢啦！

![](https://i.imgur.com/kUksdDd.jpg)

[图片备份](https://i.loli.net/2019/10/27/nDTmiP2kVgeLwaj.jpg)

**Comment by isSuperman** [comment]
字典
